# Generated by Django 5.1.1 on 2024-11-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('nombre_equipo', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField(help_text='Formato dd-mm-YYYY')),
                ('prioridad', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], max_length=1)),
                ('estado', models.IntegerField(choices=[(1, 'Terminada'), (2, 'En proceso'), (3, 'Pendiente'), (4, 'Cancelada')])),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=254)),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('L', 'Lider'), ('D', 'Desarrollador')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos_desarrollo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.equipos')),
                ('desarrollador_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas_Equipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipos_desarrollo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.equipos_desarrollo')),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tareas')),
            ],
        ),
        migrations.AddField(
            model_name='equipos',
            name='lider_usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.usuarios'),
        ),
    ]
